platform: 
  - x86 
  - x64

init:
  - ps: |
        If ($env:platform -Match "x86") {
          $env:CMAKE_GEN_PLAT="Win32"
          $env:PYTHON_ROOT="C:\Python27"
        } Else {
          $env:CMAKE_GEN_PLAT="x64"
          $env:PYTHON_ROOT="C:\Python27-x64"
        }
  - cmd: C:/"Program Files (x86)"/"Microsoft Visual Studio 12.0"/VC/vcvarsall.bat

install:
  #- choco upgrade cmake 
  #- set path=C:\Program Files\CMake\bin;%path%

before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
  - md build
  - cd build
  - cmake .. -DCMAKE_GENERATOR_PLATFORM="%CMAKE_GEN_PLAT%" 

  - cmake --build . --config Debug
  - cmake --build . --config Release

  - ctest -C Debug --output-on-failure
  - ctest -C Release --output-on-failure

  - cmake --build . --target install
