platform: 
#  - x86
  - x64

configuration:
#  - Debug
  - Release

init:
  - set path=%path%;"C:\Program Files\Microsoft SDKs\Windows\v7.1\Lib\x64"

before_build:
  - 7z x Blitz-VS2010.zip

build:
  project: Blitz-Library.sln

after_build:
  project: Blitz-Examples.sln
