
@node help
@section Mailing lists and support

@subsection How to get help
@cindex help, obtaining
@cindex support, obtaining

The starting point for all bug reports, feature requests and support
questions is the Blitz++ support page, at
@uref{http://oonumerics.org/blitz/support/}

Please note the search engine box on this web page which lets you search the
mailing list archives.  This will often turn up answers to your question if
it has been asked before.

@subsection How to subscribe to a mailing list
@cindex mailing lists

To subscribe to a Blitz++ mailing list, send a message containing one (or
more) of these lines to @email{majordomo@@oonumerics.org}:

@example
subscribe blitz-support
subscribe blitz-bugs
subscribe blitz-dev
@end example

@subsection blitz-bugs
@cindex blitz-bugs list

You can report bugs (or things you suspect might be bugs) to
@email{blitz-bugs@@oonumerics.org}.

It's not a very interesting list to be subscribed to.  There are archives
available from the Blitz++ web site.

@subsection blitz-dev
@cindex blitz-dev list
@cindex contributing to Blitz++

Blitz++ is in open development: anyone can contribute features and code to
the library.  If you are interested in helping out with coding or porting,
you should start by subscribing to the @code{blitz-dev} mailing list.  

This list is also the appropriate place to send suggestions for features;
just send email to @email{blitz-dev@@oonumerics.org}.  We can't implement it
if you don't suggest it.

Archives of this list are available from the Blitz++ web site.

@subsection blitz-support
@cindex blitz-support list

This mailing list is for posting and answering questions about using the
Blitz++ library.  Anyone can post questions; anyone can answer.

