if (NOT BLITZ_CONFIG_FILE)
    if (${CMAKE_CXX_COMPILER} MATCHES ".*xlc[+][+].*")
        set(BZ_CONFIG_FILE "apple")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*cl.*")
        set(BZ_CONFIG_FILE "ms")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*icpc.*|.*icc.*")
        set(BZ_CONFIG_FILE "intel")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*xlC.*")
        set(BZ_CONFIG_FILE "ibm")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*cxx.*")
        set(BZ_CONFIG_FILE "compaq")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*aCC.*")
        set(BZ_CONFIG_FILE "hp")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*clang[+][+].*")
        set(BZ_CONFIG_FILE "gnu")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*g[+][+].*|.*c[+][+].*")
        set(BZ_CONFIG_FILE "gnu")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*KCC.*")
        set(BZ_CONFIG_FILE "kai")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*pgCC.*")
        set(BZ_CONFIG_FILE "pgi")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*pathCC.*")
        set(BZ_CONFIG_FILE "pathscale")
    elseif (${CMAKE_CXX_COMPILER} MATCHES ".*CC.*")
        if (${CMAKE_SYSTEM_NAME} MATCHES ".*sgi.*")
            set(BZ_CONFIG_FILE "sgi")
        elseif (${CMAKE_SYSTEM_NAME} MATCHES ".*solaris.*")
            set(BZ_CONFIG_FILE "sun")
        elseif (${CMAKE_SYSTEM_NAME} MATCHES ".*cray.*")
            set(BZ_CONFIG_FILE "cray")
        elseif (${CMAKE_SYSTEM_NAME} MATCHES ".*fujitsu.*")
            set(BZ_CONFIG_FILE "fujitsu")
        endif()
    endif()

    set(BLITZ_CONFIG_INSTALL_DIR ${BZ_CONFIG_FILE})
    set(BLITZ_CONFIG_DIR "${CMAKE_CURRENT_BINARY_DIR}/blitz/${BZ_CONFIG_FILE}")
    file(MAKE_DIRECTORY ${BLITZ_CONFIG_DIR})
    set(BLITZ_CONFIG_FILE "${BLITZ_CONFIG_DIR}/bzconfig.h")
endif()
